Algoritmo "covid-19_(2)"
Var
    paises: vetor [0..14] de caractere
    mortes: vetor [0..14] de inteiro
    casos: vetor[0..14] de inteiro
    contador: inteiro
    soma, media, mediana: real
Inicio
      para contador de 0 ate 14 faca
           escreva("Digite o nome do país: ")
           leia(paises[contador])
           escreva("Digite o número de casos: ")
           leia(casos[contador])
           escreva("Digite o número de mortes: ")
           leia(mortes[contador])
      fimpara
      para contador de 0 ate 14 faca
            escreval(paises[contador], " - casos: ", casos[contador], " - mortes: ", mortes[contador])
      fimpara
      soma <- soma + casos[contador]
      media <- soma / 2
      escreval("Média dos casos: ",media)
      mediana <- casos[contador]
      escreval("Mediana dos casos: ",mediana)
Fimalgoritmo