Algoritmo "exercicios (5)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
// Seção de Declarações das variáveis 
 n1 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
ESCREVA ("Digite o numero: ")
LEIA (n1)
se n1 mod 2 = 0 entao
           escreva("O número ", n1, " é par!")
       senao
           escreva("O número ", n1, " é ímpar!")
       fimse

Fimalgoritmo