Algoritmo "exercicios (1)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2020
Var
// Seção de Declarações das variáveis 
nome, sobrenome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Nome: ")
leia(nome)
// não esqueça de dar espaço quando digitar o primeiro nome
escreva ("Sobrenome Completo: ")
leia(sobrenome)
escreva (nome + sobrenome)

Fimalgoritmo