Algoritmo "ex.(2)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
// Seção de Declarações das variáveis 
n1 : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe a temperatura atual: ")
    leia(n1)
    se n1 >= 25  entao
    escreva("Está muito quente!")
    senao
    escreva("Está agradável!")
    fimse

Fimalgoritmo