Algoritmo "ex.(1)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2020
Var
// Seção de Declarações das variáveis 
n1 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva um número: ")
       leia(n1)

       se n1 / 2 = 0 entao
           escreva("O número ", n1, " é par!")
       senao
           escreva("O número ", n1, " é ímpar!")
       fimse
Fimalgoritmo