Algoritmo "ex.(4)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2020
Var
// Seção de Declarações das variáveis 
g : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("digite o valor das vendas: ")
leia (g)
se g>=50000 entao
escreva ("Ganhou!")
senao
escreva ("Não ganhou!")
fimse
Fimalgoritmo